export function briefToMarkdown(brief, enrichedData) {
  const lines = []

  lines.push(`# ${brief.company_name} — Research Brief`)
  lines.push('')
  lines.push(`> ${brief.one_liner}`)
  lines.push('')

  lines.push('## Executive Summary')
  lines.push(brief.executive_summary)
  lines.push('')

  lines.push('## Business Model')
  lines.push(brief.business_model)
  lines.push('')

  lines.push('## Target Market')
  lines.push(brief.target_market)
  lines.push('')

  if (brief.estimated_arr) {
    lines.push(`**Estimated ARR**: ${brief.estimated_arr}`)
    lines.push('')
  }

  lines.push(`**Company Stage**: ${brief.company_stage}`)
  lines.push('')

  if (brief.pain_points?.length > 0) {
    lines.push('## Pain Points')
    for (const p of brief.pain_points) {
      lines.push(`- **${p.pain}** (${p.confidence} confidence)`)
      lines.push(`  - Evidence: ${p.evidence}`)
    }
    lines.push('')
  }

  if (brief.outreach_angles?.length > 0) {
    lines.push('## Outreach Angles')
    for (const a of brief.outreach_angles) {
      lines.push(`### ${a.approach}`)
      lines.push(`> "${a.message_hook}"`)
      lines.push(`- Reasoning: ${a.reasoning}`)
      lines.push(`- Best channel: ${a.best_channel}`)
      lines.push('')
    }
  }

  if (brief.key_contacts?.length > 0) {
    lines.push('## Key Contacts')
    for (const c of brief.key_contacts) {
      lines.push(`- **${c.name}** — ${c.title}`)
      lines.push(`  - ${c.relevance}`)
    }
    lines.push('')
  }

  if (enrichedData?.tech_stack?.length > 0) {
    lines.push('## Tech Stack')
    lines.push(enrichedData.tech_stack.join(', '))
    lines.push('')
  }

  if (brief.tech_stack_analysis) {
    lines.push('### Tech Analysis')
    lines.push(brief.tech_stack_analysis)
    lines.push('')
  }

  if (brief.competitors?.length > 0) {
    lines.push('## Competitors')
    for (const c of brief.competitors) {
      lines.push(`- **${c.competitor}**: ${c.relationship}`)
    }
    lines.push('')
  }

  if (brief.conversation_starters?.length > 0) {
    lines.push('## Conversation Starters')
    brief.conversation_starters.forEach((s, i) => {
      lines.push(`${i + 1}. ${s}`)
    })
    lines.push('')
  }

  if (brief.data_gaps?.length > 0) {
    lines.push('## Data Gaps')
    brief.data_gaps.forEach(g => lines.push(`- ${g}`))
    lines.push('')
  }

  lines.push(`---`)
  lines.push(`*Research confidence: ${brief.research_confidence} | Generated by LeadLens*`)

  return lines.join('\n')
}
